name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - /home/binary/Documents/flutter/test_app/lib/assets/icons/icon_hdpi.png
  - /home/binary/Documents/flutter/test_app/lib/assets/icons/icon_mdpi.png
  - /home/binary/Documents/flutter/test_app/lib/assets/icons/icon_xhdpi.png
  - /home/binary/Documents/flutter/test_app/lib/assets/icons/icon_xxhdpi.png
  - /home/binary/Documents/flutter/test_app/lib/assets/icons/icon_xxxhdpi.png



# flutter icon pakage
# dev_dependencies:
#   flutter_launcher_icons: ^0.10.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/"  # Path to your icon image

# images used in oroject
